# This task must not be used when there are certificates
---
- name: "StackHead::Container || Create certificates directory if not exists | Project: {{ project_name }}"
  file:
    path: "{{ stackhead__certificates_folder }}"
    state: directory

- import_tasks: "roles/stackhead_project/tasks/ssl/temp-nginx-acme-config.yml"
- import_tasks: "roles/stackhead_project/tasks/ssl/ssl-config.yml"

- name: Remove Nginx configuration for ACME
  file:
    path: "{{ stackhead__tf_project_folder }}/nginx_server_block-acme.tf"
    state: absent