---
- name: "StackHead::Container || Generate Terraform Ssl configuration file | Project: {{ containerapp__project_name }}"
  template:
    src: "templates/terraform/ssl-certificate.tf.j2"
    dest: "{{ stackhead__tf_project_folder }}/ssl-certificate.tf"
    force: true
  vars:
    domain: "{{ app_config.domain }}"
    domain_alternative: []