---
- import_tasks: "roles/stackhead_project/tasks/projectconfig-load.yml"

- import_tasks: "roles/stackhead_project/tasks/generate-ssl-certificate.yml"

- block:
  - import_tasks: "roles/stackhead_project/tasks/setup-nativeapp.yml"
    when: app_config.deployment.type == 'native'
  - import_tasks: "roles/stackhead_project/tasks/setup-dockerapp.yml"
    when: app_config.deployment.type == 'docker'
  - name: "StackHead::Project || Update deployed configuration file | Project: {{ dockerapp__project_name }}"
    import_tasks: "roles/stackhead_project/tasks/projectconfig-deploy.yml"
  when: settings_changed
