---
- include_vars: "../vars/internal.yml"
- include_vars: "../roles/stackhead_module_api/vars/main.yml"

- import_tasks: "../roles/stackhead_project/tasks/projectconfig-load.yml"

- block:
    - name: "Check if project directory exists | Project: {{ project_name }}"
      stat:
        path: "{{ stackhead__tf_project_folder }}"
      register: project_folder
    - name: "Create project directory if not exists | Project: {{ project_name }}"
      file:
        path: "{{ stackhead__tf_project_folder }}"
        state: directory
      when: project_folder.stat.exists == false and ensure == 'present'

# The following tasks will generate and deploy Terraform configuration files to the remote server
- name: "Prepare certificates directory | Project: {{ project_name }}"
  import_tasks: "../roles/stackhead_project/tasks/ssl/ssl-prepare-certificates.yml"
  when: ensure == 'present'

- block:
    - name: "Collect exposed services"
      set_fact:
        containerapp__expose: "{{ containerapp__expose|default([]) + item.expose }}"
      when: item.expose is defined and item.expose not in containerapp__expose|default([])
      with_items: "{{ app_config.domains }}"
    - import_tasks: "../roles/stackhead_module_api/tasks_internal/deployment.yml"
  when: ensure == 'present'

# Symlink Terraform configurations from project to main folder and execute them
- import_tasks: "../roles/config_terraform/tasks/update-project-symlinks.yml"
  when: ensure == 'present'
- import_tasks: "../roles/config_terraform/tasks/remove-project-symlinks.yml"
  when: ensure == 'absent'
- import_tasks: "../roles/config_terraform/tasks/execute.yml"
- file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ stackhead__project_folder }}"
    - "{{ stackhead__certificates_project_folder }}"
  when: ensure == 'absent'
