---
- include_vars: "{{ playbook_dir }}/config.yaml"

- import_tasks: "roles/stackhead_project/tasks/projectconfig-load.yml"

- name: Ensure latest compatible version of StackHead puppet module is installed
  raw: "puppet module upgrade {{ puppet_module_name }} --version '{{ puppet_module_version }}'"

- block:
    - name: "StackHead::Project || Check if project directory exists | Project: {{ project_name }}"
      stat:
        path: "{{ stackhead__puppet_project_folder }}"
      register: project_folder
    - name: "StackHead::Container || Create Puppet project directory if not exists | Project: {{ project_name }}"
      file:
        path: "{{ stackhead__puppet_project_folder }}"
        state: directory
      when: project_folder.stat.exists == false
  when: ensure == 'present'

- name: "StackHead::Project || Create certificates project directory | Project: {{ project_name }}"
  file:
    path: "{{ item }}"
    state: directory
    owner: stackhead
    group: stackhead
  with_items:
    - "{{ stackhead__certificates_project_folder }}"
    - "{{ stackhead__project_certificates_folder }}"
    - "{{ stackhead__acme_folder }}/{{ project_name }}"
  when: ensure == 'present'

# Setup project by type
- block:
  - import_tasks: "roles/stackhead_project/tasks/setup-nativeapp.yml"
    when: app_config.type == 'native'
    vars:
      ensure: "{{ ensure }}"
  - import_tasks: "roles/stackhead_project/tasks/setup-containerapp.yml"
    when: app_config.type == 'container'
    vars:
      ensure: "{{ ensure }}"

- name: "StackHead::Project || Apply puppet project manifests"
  raw: "puppet apply {{ stackhead__puppet_project_folder }}"

- name: "StackHead::Container || Remove Puppet project directory| Project: {{ project_name }}"
  file:
    path: "{{ stackhead__puppet_project_folder }}"
    state: absent
  when: ensure == 'absent'
- name: "StackHead::Project || Remove certificates project directory | Project: {{ project_name }}"
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ stackhead__certificates_project_folder }}"
    - "{{ stackhead__project_certificates_folder }}"
    - "{{ stackhead__acme_folder }}/{{ project_name }}"
  when: ensure == 'absent'