---
# the variable "app_config" is part of the StackHead module API (update documentation if changed)
- name: "StackHead::Project || Extract application information (looking in {{ stackhead__config_folder }})"
  include_vars:
    file: "{{ lookup('first_found', params) }}"
    name: app_config
  vars:
    params:
      files:
        - "{{ project_name }}.stackhead.yml"
        - "{{ project_name }}.stackhead.yaml"
      paths:
        - "{{ stackhead__config_folder }}"
  delegate_to: 127.0.0.1
