---
- import_tasks: "roles/stackhead_setup/tasks/facts-load.yml"

- name: "StackHead::Project || Extract application information"
  include_vars:
    file: "{{ stackhead__local_config_file }}"
    name: app_config
  delegate_to: 127.0.0.1
