---
- name: "StackHead::Project || Setup nativeapp"
  import_role:
    name: project_nativeapp
  vars:
    nativeapp__project_name: "{{ project_name }}"
    nativeapp__public_path: "{{ app_config.deployment.settings.public_path }}" # todo: remove

- name: "StackHead::Project || Update Nginx vhost configuration"
  include_role:
    name: config_nginx
  vars:
    nginx_use_php: "{{ native_php_enabled }}"