---
- name: "StackHead::Project || Collect exposed services"
  set_fact:
    containerapp__expose: "{{ containerapp__expose|default([]) + item.expose }}"
  when: item.expose is defined and item.expose not in containerapp__expose
  with_items: "{{ app_config.domains }}"
- name: "StackHead::Project || Setup Container app"
  import_role:
    name: project_containerapp
  vars:
    ensure: "{{ ensure }}"
    containerapp__project_name: "{{ project_name }}"
    containerapp__services: "{{ app_config.container.services }}"
    containerapp__registries: "{{ app_config.container.registries | default([]) }}"