---
type: native
domains:
  - domain: ${domain}
    public_path: html
    security:
      authentication:
        - type: basic
          username: user
          password: pass
native:
  capabilities:
    php:
      version: 7.3
