---
deployment:
  - ansible/roles/stackhead_project/**/*
  - ansible/roles/config_terraform/**/*
  - ansible/playbooks/application-*.yml
module-api:
  - ansible/roles/stackhead_module_api/**/*
setup:
  - ansible/roles/stackhead_setup/**/*
  - ansible/playbooks/server-*.yml
dependencies:
  - ansible/requirements/**/*
documentation:
  - Documentation/**/*.md
cli:
  - cli/**/*
