name: 'StackHead Acceptance Test'
description: 'Perform StackHead acceptance test'
inputs:
  ipaddress:
    description: 'IP address of the server'
    required: true
  domain:
    description: 'Domain'
    required: true
  domain2:
    description: 'Second domain'
    required: true
  webserver:
    description: 'Webserver module to use'
    required: true
  rolename:
    description: 'Name of role that is being tested'
    required: false
runs:
  using: "composite"
  steps:
    - name: Add IP to known_hosts
      shell: bash
      run: "ssh-keyscan -v -T 30 ${{ inputs.ipaddress }} >> ~/.ssh/known_hosts"
    - name: "Test step: Provision server"
      shell: bash
      env:
        INPUT_IPADDRESS: ${{ inputs.ipaddress }}
        INPUT_WEBSERVER: ${{ inputs.webserver }}
        INPUT_ROLENAME: ${{ inputs.rolename }}
      run: ${{ github.action_path }}/ansible/__tests__/steps/test_provision.sh
    - name: "Test step: Deploy application"
      shell: bash
      run: ${{ github.action_path }}/ansible/__tests__/steps/test_deploy.sh
      env:
        INPUT_IPADDRESS: ${{ inputs.ipaddress }}
        INPUT_DOMAIN: ${{ inputs.domain }}
        INPUT_DOMAIN2: ${{ inputs.domain2 }}
        INPUT_WEBSERVER: ${{ inputs.webserver }}
    - name: "Test step: Validate deployment"
      shell: bash
      run: ${{ github.action_path }}/ansible/__tests__/steps/test_validate-deployment.sh
      env:
        INPUT_DOMAIN: ${{ inputs.domain }}
        INPUT_DOMAIN2: ${{ inputs.domain2 }}
    - name: "Test step: Destroy deployment"
      shell: bash
      run: ${{ github.action_path }}/ansible/__tests__/steps/test_destroy.sh
