name: 'StackHead Acceptance Test'
description: 'Perform StackHead acceptance test'
inputs:
  ipaddress:
    description: 'IP address of the server'
    required: true
  domain:
    description: 'Domain'
    required: true
  domain2:
    description: 'Second domain'
    required: true
  webserver:
    description: 'Webserver module to use'
    required: true
  container:
    description: 'Container module to use'
    required: false
    default: getstackhead.stackhead_container_docker
  rolename:
    description: 'Name of role that is being tested'
    required: false
  selftest:
    description: 'Set if this test is run on the StackHead main repository'
    required: false
runs:
  using: "composite"
  steps:
    - name: Add IP to known_hosts
      shell: bash
      run: "ssh-keyscan -v -T 30 ${{ inputs.ipaddress }} >> ~/.ssh/known_hosts"
    - name: "Build collection and install dependencies"
      shell: bash
      env:
        INPUT_ROLENAME: ${{ inputs.rolename }}
      run: ${{ github.action_path }}/ansible/__tests__/steps/build.sh
    - name: "Setup server"
      shell: bash
      env:
        INPUT_IPADDRESS: ${{ inputs.ipaddress }}
        INPUT_WEBSERVER: ${{ inputs.webserver }}
        INPUT_CONTAINER: ${{ inputs.container }}
        INPUT_ROLENAME: ${{ inputs.rolename }}
        INPUT_SELFTEST: ${{ inputs.selftest }}
      run: ${{ github.action_path }}/ansible/__tests__/steps/setup.sh
    - name: "Deploy application"
      shell: bash
      run: ${{ github.action_path }}/ansible/__tests__/steps/deploy.sh
      env:
        INPUT_IPADDRESS: ${{ inputs.ipaddress }}
        INPUT_DOMAIN: ${{ inputs.domain }}
        INPUT_DOMAIN2: ${{ inputs.domain2 }}
        INPUT_WEBSERVER: ${{ inputs.webserver }}
        INPUT_CONTAINER: ${{ inputs.container }}
    - name: "Validate deployment"
      shell: bash
      run: ${{ github.action_path }}/ansible/__tests__/steps/validate.sh
      env:
        INPUT_DOMAIN: ${{ inputs.domain }}
        INPUT_DOMAIN2: ${{ inputs.domain2 }}
    - name: "Destroy deployment"
      shell: bash
      run: ${{ github.action_path }}/ansible/__tests__/steps/destroy.sh
