---
- set_fact:
    plugin_list: "{{ plugin_list|default([]) + [{'name': item, 'group': 'plugin', 'optional': true}] }}"
  when: item != ''
  with_items: "{{ stackhead_config.plugins }}"
- include_tasks: "../roles/stackhead_module_api/tasks_internal/execute-module-step.yml"
  vars:
    stackhead_action: "deploy"
  loop_control:
    loop_var: module
  with_items:
    - { name: "{{ stackhead_config.container }}", group: 'container management', optional: false }
    - { name: '{{ stackhead_config.webserver }}', group: 'webserver', optional: false }
    - "{{ plugin_list|default([]) }}"
