---
- set_fact:
    destroy_plugin_list: "{{ destroy_plugin_list|d([]) + [{'name': item, 'group': 'plugin', 'optional': false, 'config': stackhead_config.destroy[item]|d([])}]}]}] }}"
  when: item != None
  with_items: "{{ stackhead_config.plugins }}"
- set_fact:
    destroy_dns_list: "{{ destroy_dns_list|d([]) + [{'name': item, 'group': 'DNS', 'optional': false, 'config': stackhead_config.destroy[item]|d([])}] }}"
  when: item != None
  with_items: "{{ stackhead_config.dns }}"
- include_tasks: "../roles/stackhead_module_api/tasks_internal/execute-module-step.yml"
  vars:
    stackhead_action: "destroy"
  when: module.name != None
  loop_control:
    loop_var: module
  with_items:
    - "{{ destroy_dns_list|d([]) }}"
    - { name: "{{ stackhead_config.container }}", group: 'container management', optional: true, config: "{{ stackhead_config.destroy[stackhead_config.container]|d([]) }}" }
    - { name: '{{ stackhead_config.webserver }}', group: 'webserver', optional: true, config: "{{ stackhead_config.destroy[stackhead_config.webserver]|d([]) }}" }
    - "{{ destroy_plugin_list|d([]) }}"
