---
- include_tasks: "../roles/stackhead_module_api/tasks_internal/execute-module-step.yml"
  vars:
    stackhead_action: "destroy"
    module_name: "{{ item.name }}"
    module_group: "{{ item.group }}"
  with_items:
    - { name: "{{ stackhead_config.container }}", group: 'container management' }
    - { name: '{{ stackhead_config.webserver }}', group: 'webserver' }
