---
- set_fact:
    plugin_list: "{{ plugin_list|default([]) + [{'name': item, 'group': 'plugin'}] }}"
  with_items: "{{ stackhead_config.plugins }}"
- include_tasks: "../roles/stackhead_module_api/tasks_internal/execute-module-step.yml"
  vars:
    stackhead_action: "destroy"
    module_name: "{{ item.name }}"
    module_group: "{{ item.group }}"
    optional: true
  with_items:
    - { name: "{{ stackhead_config.container }}", group: 'container management' }
    - { name: '{{ stackhead_config.webserver }}', group: 'webserver' }
    - "{{ plugin_list|default([]) }}"
