---
- set_fact:
    plugin_list: "{{ plugin_list|default([]) + [{'name': item, 'group': 'plugin', 'optional': false, 'config': stackhead_config.destroy[item]|default([])}]}]}] }}"
  when: item != ''
  with_items: "{{ stackhead_config.plugins }}"
- include_tasks: "../roles/stackhead_module_api/tasks_internal/execute-module-step.yml"
  vars:
    stackhead_action: "destroy"
  loop_control:
    loop_var: module
  with_items:
    - { name: "{{ stackhead_config.container }}", group: 'container management', optional: true, config: "{{ stackhead_config.destroy[stackhead_config.container]|default([]) }}" }
    - { name: '{{ stackhead_config.webserver }}', group: 'webserver', optional: true, config: "{{ stackhead_config.destroy[stackhead_config.webserver]|default([]) }}" }
    - "{{ plugin_list|default([]) }}"
