---
- getstackhead.stackhead.module_load_config:
    name: "{{ module_name }}"
  register: loaded_config
- include_tasks: "{{ stackhead__roles }}/stackhead_module_api/tasks_internal/validate-module-constraints.yml"
  vars:
    module_config: "{{ loaded_config.config_varname }}"
- name: "{{ stackhead_action }} {{ module_group }} ({{ module_name }}) configuration"
  include_tasks: "{{ module_role_path }}/tasks/steps/{{ stackhead_action }}.yml"
  vars:
    module_role_path: "{{ lookup('getstackhead.stackhead.role_path', module_name) }}"
