---
- set_fact:
    plugin_list: "{{ plugin_list|d([]) + [{'name': item, 'group': 'plugin', 'config': stackhead_config.setup[item]|d([])}] }}"
  when: item != ''
  with_items: "{{ stackhead_config.plugins }}"
- include_tasks: "../roles/stackhead_module_api/tasks_internal/execute-module-step.yml"
  vars:
    stackhead_action: "setup"
  loop_control:
    loop_var: module
  with_items:
    - { name: "{{ stackhead_config.container }}", group: 'container management', config: "{{ stackhead_config.setup[stackhead_config.container]|d([]) }}" }
    - { name: '{{ stackhead_config.webserver }}', group: 'webserver', config: "{{ stackhead_config.setup[stackhead_config.webserver]|d([]) }}" }
    - "{{ plugin_list|d([]) }}"
