---
- set_fact:
    setup_plugin_list: "{{ setup_plugin_list|d([]) + [{'name': item, 'group': 'plugin', 'config': stackhead_config.setup[item]|d([])}] }}"
  when: item != None
  with_items: "{{ stackhead_config.plugins }}"
- set_fact:
    setup_dns_list: "{{ setup_dns_list|d([]) + [{'name': item, 'group': 'DNS', 'optional': true, 'config': stackhead_config.setup[item]|d([])}] }}"
  when: item != None
  with_items: "{{ stackhead_config.dns }}"
- include_tasks: "../roles/stackhead_module_api/tasks_internal/execute-module-step.yml"
  vars:
    stackhead_action: "setup"
  when: module != None and module.name != ''
  loop_control:
    loop_var: module
  with_items:
    - "{{ setup_dns_list|d([]) }}"
    - { name: "{{ stackhead_config.container }}", group: 'container management', config: "{{ stackhead_config.setup[stackhead_config.container]|d([]) }}" }
    - { name: '{{ stackhead_config.webserver }}', group: 'webserver', config: "{{ stackhead_config.setup[stackhead_config.webserver]|d([]) }}" }
    - "{{ setup_plugin_list|d([]) }}"
