---
- set_fact:
    tf_dns_list: "{{ tf_dns_list|d([]) + [{'name': item, 'group': 'DNS' }] }}"
  when: item != None
  with_items: "{{ stackhead_config.dns }}"
- include_tasks: "../roles/stackhead_module_api/tasks_internal/terraform/module.yml"
  when: module != None
  loop_control:
    loop_var: module
  with_items:
    - "{{ tf_dns_list|d([]) }}"
    - { name: "{{ stackhead_config.container }}", group: 'container management' }
    - { name: '{{ stackhead_config.webserver }}', group: 'webserver' }
