---
- include_tasks: "../roles/stackhead_module_api/tasks_internal/terraform/module.yml"
  loop_control:
    loop_var: module
  with_items:
    - { name: "{{ stackhead_config.container }}", group: 'container management' }
    - { name: '{{ stackhead_config.webserver }}', group: 'webserver' }
