---
- name: "StackHead::Project || Find all project related Puppet symlinks | Project: {{ project_name }}"
  find:
    paths: "{{ stackhead__puppet_root_folder }}"
    recurse: no
    patterns: "^project_{{ project_name }}_.*\\.pp"
    file_type: link
    use_regex: yes
  register: project_puppet_symlinks
- name: "StackHead::Project || Remove project symlinks | Project: {{ project_name }}"
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ project_puppet_symlinks.files }}"