---
- name: "StackHead::Project || Find all current project Terraform files | Project: {{ project_name }}"
  find:
    paths: "{{ stackhead__tf_project_folder }}"
    recurse: no
    patterns: "*.tf"
  register: project_tf_files
- name: "StackHead::Project || Create new symlinks | Project: {{ project_name }}"
  file:
    src: "{{ item.path }}"
    dest: "{{ stackhead__tf_root_folder }}/project_{{ project_name }}_{{ item.path | basename }}"
    state: link
  with_items: "{{ project_tf_files.files }}"