---
- name: "StackHead::Project || Find all project related Terraform symlinks | Project: {{ project_name }}"
  find:
    paths: "{{ stackhead__tf_root_folder }}"
    recurse: no
    patterns: "^project_{{ project_name }}_.*\\.tf$"
    file_type: link
    use_regex: yes
  register: project_tf_symlinks
- name: "StackHead::Project || Remove project symlinks | Project: {{ project_name }}"
  file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ project_tf_symlinks.files }}"