---
- name: "StackHead::Project || Find all current project Terraform files | Project: {{ project_name }}"
  find:
    paths: "{{ stackhead__tf_project_folder }}"
    recurse: no
    patterns: "*.tf"
  register: project_tf_files_all
- name: "StackHead::Project || Find all known project terraform files | Project: {{ project_name }}"
  find:
    paths: "{{ stackhead__tf_root_folder }}"
    recurse: no
    patterns: "project_{{ project_name }}_*.tf"
    file_type: link
  register: project_tf_files_known
- name: "Create missing project Terraform files"
  file:
    src: "{{ item }}"
    dest: "{{ stackhead__tf_root_folder }}/{{ file_name }}"
    state: link
  when: file_name not in project_tf_files_known.files | map(attribute='path') | map('basename') | list
  vars:
    file_name: "project_{{ project_name }}_{{ item | basename }}"
  with_items: "{{ project_tf_files_all.files | map(attribute='path') | list }}"
- name: "Remove project Terraform files not needed anymore"
  file:
    path: "{{ item }}"
    state: absent
  when: item | replace('project_' ~ project_name ~ '_','') not in project_tf_files_all.files | map(attribute='path') | map('basename') | list
  with_items: "{{ project_tf_files_known.files | map(attribute='path') | map('basename') | list }}"
