# inventory for integration test
---
all:
  vars:
    stackhead__config_folder: "{{ inventory_dir }}/projects"
    stackhead__webserver: ${webserver}
    stackhead__container: ${container}
    stackhead__plugins: []
    ansible_user: root
    ansible_connection: ssh
    ansible_python_interpreter: /usr/bin/python3
  hosts:
    hetzner1:
      ansible_host: ${ipaddress}
      stackhead:
        applications:
          - ${application}
