# This unit test validates that the major version check works and process aborts if needed
---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    unittest_file: "../roles/stackhead_project/tasks/validate-stackhead-version.yml"
  tasks:
    - include_tasks: "./unit/unittest_base.yml"
      vars:
        stackhead_config:
          version:
            installed: "{{ item.installed }}"
            current: "{{ item.current }}"
      with_items:
        - name: "No install version can be found"
          installed: ""
          current: 2.1.0
          result: 0
        - name: "Current version has a higher major version than the version used for setup"
          installed: 1.0.0
          current: 2.1.0
          result: 0
        - name: "Current version has a higher major version than the version used for setup (with version suffix)"
          installed: 1.0.0
          current: 2.1.0-dev
          result: 0
        - name: "Current version has an equal major version as the version used for setup"
          installed: 1.0.0
          current: 1.2.3
          result: 1
        - name: "Current version has an equal major version as the version used for setup (with version suffix)"
          installed: 1.0.0
          current: 1.2.3-dev
          result: 1
