---
- hosts: localhost
  connection: local
  tasks:
    - include_vars: "./variables.yml"
    - include_vars: "{{ playbook_dir }}/../vars/internal.yml"
    - include_vars: "{{ playbook_dir }}/../roles/stackhead_module_api/vars/main.yml"
    - set_fact:
        stackhead__templates: "{{ playbook_dir }}/../templates"
    - name: "Test SSL Terraform file generation"
      template:
        src: "{{ stackhead__templates }}/terraform/ssl-certificate.tf.j2"
        dest: "./ssl-certificate.tf"
      vars:
        stackhead__acme_folder: ""
        stackhead__project_certificates_folder: ".stackhead/projects/{{ project_name }}/certificates"
        stackhead__certificates_project_folder: ".stackhead/certificates/{{ project_name }}"
        stackhead__tf_project_folder: "/stackhead-root/projects/test/terraform"
