---
- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
    - include_vars: "../roles/stackhead_module_api/testdata/variables.yml"
    - include_vars: "../vars/internal.yml"
    - include_vars: "../roles/stackhead_module_api/vars/main.yml"
    - set_fact:
        stackhead__templates: "{{ playbook_dir }}/../templates"
    - set_fact:
        containerapp__expose: "{{ containerapp__expose|default([]) + item.expose }}"
      when: item.expose is defined and item.expose not in containerapp__expose|default([])
      with_items: "{{ app_config.domains }}"
    - name: "Test filter plugin"
      template:
        src: "templates/filterplugin.txt.j2"
        dest: "filterplugin.txt"
    - name: "Test SSL Terraform file generation"
      template:
        src: "{{ stackhead__templates }}/terraform/ssl-certificate.tf.j2"
        dest: "./ssl-certificate.tf"
      vars:
        stackhead__acme_folder: ""
        stackhead__roles: "{{ playbook_dir }}/../roles"
        stackhead__project_certificates_folder: ".stackhead/projects/{{ project_name }}/certificates"
        stackhead__certificates_project_folder: ".stackhead/certificates/{{ project_name }}"
        stackhead__tf_project_folder: "/stackhead-root/projects/test/terraform"
    - name: "Test Terraform provider file generation"
      template:
        src: "{{ stackhead__templates }}/terraform/terraform-providers.tf.j2"
        dest: "./terraform-providers.tf"
      vars:
        loaded_terraform_providers:
          - name: test
            vendor: test
            version: 1.0
          - name: test2
            vendor: test
            version: 1.1-dev
            init: 'test_files/some-provider.tf.j2'
