---
- name: "StackHead::Project || Create SSL certificate"
  include_role:
    name: geerlingguy.certbot
    apply:
      become: yes
      become_user: root # installing certbot requires root. # @TODO: move installation into provisioning
  vars:
    certbot_create_if_missing: true
    certbot_create_method: standalone
    certbot_create_standalone_stop_services:
      - nginx
    certbot_certs:
      - email: certificate@saitho.me
        domains:
          - "{{ app_config.domain }}"
