---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  ignore_errors: yes

- set_fact:
    has_basic_auth: "{{ nginx_auth_basic is defined and nginx_auth_basic | length > 0 }}"
    htpasswd_path: "{{ nginx_htpasswd_path }}/.{{ project_name }}"

- name: Generate htpasswd Terraform file
  template:
    src: "templates/terraform/htpasswd.tf.j2"
    dest: "{{ stackhead__tf_project_folder }}/htpasswd.tf"
    force: true
  when: has_basic_auth

- name: Generate nginx vhost Terraform file
  template:
    src: "templates/terraform/nginx_server_block.tf.j2"
    dest: "{{ stackhead__tf_project_folder }}/nginx_server_block.tf"
    force: true
  vars:
    nginx_vhost_content: "{{ lookup('template', nginx_vhost_template) }}"
    resource_name: "{{ project_name }}"

