---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  ignore_errors: yes

- set_fact:
    has_basic_auth: "{{ nginx_auth_basic is defined and nginx_auth_basic | length > 0 }}"
    htpasswd_path: "{{ nginx_htpasswd_path }}/.{{ nginx_project_name }}"

- name: Write BasicAuth data
  htpasswd:
    path: "{{ htpasswd_path }}"
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    state: present
  when: item.type == 'basic'
  with_items: "{{ nginx_auth_basic }}"

- name: Remove BasicAuth file
  file:
    path: "{{ htpasswd_path }}"
    state: absent
  when: not has_basic_auth

- name: Add managed vhost config files.
  template:
      src: "{{ nginx_vhost_template }}"
      dest: "{{ nginx_vhost_path }}/{{ item.filename|default(item.server_name.split(' ')[0] ~ '.conf') }}"
      force: true
      mode: 0644
  when: item.state|default('present') != 'absent'
  with_items: "{{ nginx_vhosts }}"
  notify: reload nginx
  tags:
      - template
- name: Remove managed vhost config files.
  file:
      path: "{{ nginx_vhost_path }}/{{ item.filename|default(item.server_name.split(' ')[0] ~ '.conf') }}"
      state: absent
  when: item.state|default('present') == 'absent'
  with_items: "{{ nginx_vhosts }}"
  notify: reload nginx
