---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  ignore_errors: yes

- set_fact:
    has_basic_auth: "{{ nginx_auth_basic is defined and nginx_auth_basic | length > 0 }}"
    htpasswd_path: "{{ nginx_htpasswd_path }}/.{{ nginx_project_name }}"

- name: Generate htpasswd Terraform file
  template:
    src: "templates/terraform/htpasswd.tf.j2"
    dest: "{{ containerapp__project_src }}/terraform/htpasswd.tf"
    force: true
  when: has_basic_auth

- name: Add managed vhost config files.
  template:
      src: "{{ nginx_vhost_template }}"
      dest: "{{ nginx_vhost_path }}/{{ item.filename|default(item.server_name.split(' ')[0] ~ '.conf') }}"
      force: true
      mode: 0644
  when: item.state|default('present') != 'absent'
  with_items: "{{ nginx_vhosts }}"
  notify: reload nginx
  tags:
      - template
- name: Remove managed vhost config files.
  file:
      path: "{{ nginx_vhost_path }}/{{ item.filename|default(item.server_name.split(' ')[0] ~ '.conf') }}"
      state: absent
  when: item.state|default('present') == 'absent'
  with_items: "{{ nginx_vhosts }}"
  notify: reload nginx
