---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  ignore_errors: yes

- name: Add managed vhost config files.
  template:
      src: "{{ nginx_vhost_template }}"
      dest: "{{ nginx_vhost_path }}/{{ item.filename|default(item.server_name.split(' ')[0] ~ '.conf') }}"
      force: true
      mode: 0644
  when: item.state|default('present') != 'absent'
  with_items: "{{ nginx_vhosts }}"
  notify: reload nginx
  tags:
      - template
- name: Remove managed vhost config files.
  file:
      path: "{{ nginx_vhost_path }}/{{ item.filename|default(item.server_name.split(' ')[0] ~ '.conf') }}"
      state: absent
  when: item.state|default('present') == 'absent'
  with_items: "{{ nginx_vhosts }}"
  notify: reload nginx
