- name: geerlingguy.docker
  version: 2.8.1
- name: andrewrothstein.terraform
  version: v2.2.43
- name: getstackhead.stackhead_container_docker
  src: https://github.com/getstackhead/module-container-docker
- name: getstackhead.stackhead_webserver_nginx
  src: https://github.com/getstackhead/module-webserver-nginx
- name: getstackhead.stackhead_webserver_caddy
