# excluded to own file as we can't look blocks...
---
- set_fact:
    loaded_config: "{{ ansible_facts[module.name | getstackhead.stackhead.module_vars_name] }}"
- set_fact:
    loaded_terraform_providers: "{{ loaded_terraform_providers|default([]) + [tf_provider] }}"
  when: tf_provider.name is defined and  tf_provider.vendor is defined and tf_provider.version is defined and not tf_provider.provider_per_project|d(false)
  vars:
    tf_provider: "{{ loaded_config.terraform.provider|default({}) }}"
