---
- include_tasks: "../roles/stackhead_module_api/tasks_internal/load-plugin-config.yml"
  vars:
    plugin_config_name: "{{ module_name }}"
- debug:
    msg: "{{ module_vars }}"
- block:
    - set_fact:
        loaded_terraform_providers: "{{ loaded_terraform_providers|default([]) + [module_vars.terraform.provider|combine({'module_name': module_name})] }}"
  when: module_vars.terraform is defined and module_vars.terraform.provider is defined and module_vars.terraform.provider.name and module_vars.terraform.provider.vendor is defined and module_vars.terraform.provider.version is defined
- debug:
    msg: "{{ loaded_terraform_providers }}"
