---
- name: "Check required variables provider_old and provider_new"
  assert:
    that:
      - provider_old|d("") != ""
      - provider_old_version|d("") != ""
      - provider_new|d("") != ""
- include_tasks: "{{ stackhead__roles }}/config_terraform/tasks/replace-provider.yml"
  with_items:
    - "{{ stackhead__tf_root_folder }}"
    - "{{ stackhead__system_tf_root_folder }}"
