---
- hosts: all
  become_user: stackhead
  tasks:
    - include_role:
        name: getstackhead.stackhead.stackhead_project
      loop_control:
        loop_var: project_name
        # the variable "project_name" is part of the StackHead module API (update documentation if changed)
      with_items: "{{ stackhead.applications }}"
      vars:
        ensure: 'present'
