---
- include_tasks: "../roles/stackhead_module_api/tasks_internal/execute-module-step.yml"
  vars:
    stackhead_action: "remove-syscontainer"
    module:
      name: "{{ stackhead_config.container }}"
      group: "container"
- include_tasks: "{{ stackhead__roles }}/stackhead_module_api/tasks_internal/terraform/update-system-terraform.yml"
