---
- name: Update apt caches
  apt:
    update_cache: yes
- import_role:
    name: andrewrothstein.python
- import_role:
    name: nickjj.docker
  vars:
    docker__users: ["{{ ansible_env.SUDO_USER | d('root') }}", "stackhead"]
