---
- hosts: all
  become_user: stackhead
  vars:
    stackhead__project_folder: "/stackhead/projects/{{ project_name }}" # temporary
  tasks:
    - include_vars: "{{ playbook_dir }}/config.yaml"
    - include_tasks: "roles/config_terraform/tasks/remove-project-symlinks.yml"
    - import_tasks: "roles/config_terraform/tasks/execute.yml"
    - file:
        path: "{{ stackhead__project_folder }}"
        state: absent
