# Global variable configurations accessible by all roles
---
# StackHead
stackhead__templates: "{{ playbook_dir }}/templates"
stackhead__root_folder: "/stackhead"
stackhead__bin_location: "{{ stackhead__root_folder }}/bin"

# Terraform
stackhead__tf_root_folder: "{{ stackhead__root_folder }}/terraform/"

# Puppet
stackhead__puppet_root_folder: "{{ stackhead__root_folder }}/puppet/"
puppet_module_name: "getstackhead-stackhead"
puppet_module_version: ">=1.0.0 <2.0.0"

# Python
ansible_python_interpreter: /usr/bin/python3

# SSL certificates
stackhead__certificates_folder: "{{ stackhead__root_folder }}/certificates"
stackhead__snakeoil_privkey: "{{ stackhead__certificates_folder }}/privkey_snakeoil.pem"
stackhead__snakeoil_fullchain: "{{ stackhead__certificates_folder }}/fullchain_snakeoil.pem"
stackhead__snakeoil_certrequest_tmp: "{{ stackhead__certificates_folder }}/certrequest_snakeoil.pem"
stackhead__acme_folder: "{{ stackhead__root_folder }}/acme-challenges"

# Nginx
nginx_htpasswd_path: /etc/nginx/passwd