namespace: "getstackhead"
name: "stackhead"
version: "0.0.0"
authors:
  - "Mario Lubenka <mario.lubenka@googlemail.com>"
tags:
  - demo
  - collection
readme: "README.md"
license: "GPL-2.0"
repository: "https://github.com/getstackhead/stackhead"
documentation: "http://docs.stackhead.io/"
build_ignore:
  - __tests__
