namespace: "getstackhead"
name: "stackhead"
version: "0.0.0"
authors:
  - "Mario Lubenka <mario.lubenka@googlemail.com>"
dependencies:
  "geerlingguy.docker": ">=2.8.1,<3.0.0"
  "geerlingguy.nginx": ">=2.8.0,<3.0.0"
  "andrewrothstein.terraform": ">=2.2.43,<3.0.0"
tags:
  - demo
  - collection
readme: "../README.md"
license_file: "../LICENSE"
repository: "https://github.com/getstackhead/stackhead"
documentation: "http://docs.stackhead.io/"
#build_ignore:
#  - __tests__