---
- include_tasks: "{{ item.src }}"

# update lockfile and migration state
- lineinfile:
    path: "{{ lockfile_path }}"
    line: "{{ item.path }}"
    state: present
    create: yes
- set_fact:
    done_migrations: "{{ done_migrations + [item.path] }}"
