---
nginx_vhost_template: "{{ playbook_dir }}/templates/nginx-vhost.j2"
nginx_tf_template: "{{ playbook_dir }}/templates/terraform/nginx_server_block.tf.j2"
nginx_basicauth_title: "Restricted area"
nginx_dockerapp: 0