---
- block:
  - name: "StackHead::Container || Check if project directory exists | Project: {{ containerapp__project_name }}"
    stat:
      path: "{{ containerapp__project_src }}"
    register: project_folder
  - name: "StackHead::Container || Create project directory if not exists | Project: {{ containerapp__project_name }}"
    file:
      path: "{{ containerapp__project_src }}"
      state: directory
    when: project_folder.stat.exists == false

- block:
  - name: "StackHead::Container || Build src folder list || Project: {{ containerapp__project_name }}"
    block:
      - name: "Collect local volumes"
        set_fact:
          managedContainerVolumePaths: "{{ managedContainerVolumePaths|default([]) + [ ''~ containerapp__data_location_services|format(item.0.name, item.1.src|default()) ~'' ] }}"
        when: item.1.type == 'local'
        with_subelements:
          - "{{ containerapp__services }}"
          - volumes
          - flags:
            skip_missing: True
      - name: "Collect global volumes"
        set_fact:
          managedContainerVolumePaths: "{{ managedContainerVolumePaths|default([]) + [ '' ~ containerapp__data_location_global|format(item.1.src|default()) ~ '' ] }}"
        when: item.1.type == 'global'
        with_subelements:
          - "{{ containerapp__services }}"
          - volumes
          - flags:
            skip_missing: True
      - name: "Collect custom volumes"
        set_fact:
          managedContainerVolumePaths: "{{ managedContainerVolumePaths|default([]) + [ '' ~ item.1.src ~ '' ] }}"
        when: item.1.type == 'custom'
        with_subelements:
          - "{{ containerapp__services }}"
          - volumes
          - flags:
            skip_missing: True
  - name: "StackHead::Container || Authenticate with Docker registries || Project: {{ containerapp__project_name }}"
    docker_login:
      username: "{{ item.username }}"
      password: "{{ item.password }}"
      url: "{{ item.url | default('https://index.docker.io/v1/') }}"
      reauthorize: yes
    with_items: "{{ containerapp__registries }}"
  - name: "StackHead::Container || Pull required images || Project: {{ containerapp__project_name }}"
    docker_image:
      name: "{{ item.image }}"
      source: pull
      force_source: yes
    with_items: "{{ containerapp__services }}"
    vars:
      ansible_python_interpreter: "/usr/bin/env python-docker"
  - block:
      - name: "StackHead::Container || Checking volume folders"
        stat:
          path: "{{ item }}"
        register: folder_stats
        with_items: "{{ managedContainerVolumePaths }}"
      - name: "StackHead::Container || Creating missing volume folders"
        file:
          path: "{{ item.item }}"
          state: directory
          mode: 0755
        when: item.stat.exists == false
        with_items: "{{ folder_stats.results }}"
    when: managedContainerVolumePaths is defined

- block:
  - name: "StackHead::Container || Tear down existing services | Project: {{ containerapp__project_name }}"
    docker_compose:
      project_src: "{{ containerapp__project_src }}"
      state: absent
      files:
        - docker-compose.base.yml
        - docker-compose.volumes.yml
    ignore_errors: yes
    vars:
      ansible_python_interpreter: "/usr/bin/env python-docker"

  - block:
      - name: "StackHead::Container || Generate docker-compose volumes file | Project: {{ containerapp__project_name }}"
        template:
          src: "templates/docker-compose.base.yml.j2"
          dest: "{{ containerapp__project_src }}/docker-compose.base.yml"
          force: true
        tags:
          - template
      - name: "StackHead::Container || Generate docker-compose base file | Project: {{ containerapp__project_name }}"
        template:
          src: "templates/docker-compose.volumes.yml.j2"
          dest: "{{ containerapp__project_src }}/docker-compose.volumes.yml"
          force: true
        tags:
          - template

  - name: "StackHead::Container || Create and start services | Project: {{ containerapp__project_name }}"
    docker_compose:
      project_src: "{{ containerapp__project_src }}"
      files:
        - docker-compose.base.yml
        - docker-compose.volumes.yml
    vars:
      ansible_python_interpreter: "/usr/bin/env python-docker"
  when: containerapp__file_changed == true

# Always fetch port - required for Nginx config update when domain changed
- block:
  - name: "StackHead::Container || Get current Docker port"
    shell: "docker port stackhead-{{ project_name }}-{{ item.name }} {{ containerapp__expose.port }}"
    when: containerapp__expose is defined and item.name == containerapp__expose.service
    with_items: "{{ containerapp__services }}"
    register: used_port

  - set_fact:
      container_port: "{{ item.stdout | replace('0.0.0.0:','') }}"
    when: item.changed == true
    with_items: "{{ used_port.results }}"
