---
# Create certificates directory
- file:
    path: "{{ stackhead__certificates_folder }}"
    state: directory
- stat:
    path: "{{ stackhead__certificates_folder }}/fullchain.pem"
  register: cert_exists
# Generate a Self Signed OpenSSL certificate to be able to start up Nginx
- block:
  - openssl_privatekey:
        path: "{{ stackhead__certificates_folder }}/privkey.pem"
  - openssl_csr:
        path: "{{ stackhead__certificates_folder }}/fakecert_request.pem"
        privatekey_path: "{{ stackhead__certificates_folder }}/privkey.pem"
        common_name: "dummy-cert"
  - openssl_certificate:
        path: "{{ stackhead__certificates_folder }}/fullchain.pem"
        privatekey_path: "{{ stackhead__certificates_folder }}/privkey.pem"
        csr_path: "{{ stackhead__certificates_folder }}/fakecert_request.pem"
        provider: selfsigned
  - file:
        path: "{{ stackhead__certificates_folder }}/fakecert_request.pem"
        state: absent
  when: cert_exists.stat.exists == false
