---
# Set up basic nginx that can handle ACME requests
- name: Generate nginx ACME challenge configuration Terraform file
  template:
    src: "{{ stackhead__templates }}/terraform/nginx_server_block.tf.j2"
    dest: "{{ stackhead__tf_project_folder }}/nginx_server_block-acme.tf"
    force: true
  vars:
    nginx_dockerapp: 0
    nginx_usehttps: 0
    nginx_servername: "{{ app_config.domains[0].domain }}"
    resource_name: "__acme-{{ project_name }}"

- import_tasks: "roles/config_terraform/tasks/update-project-symlinks.yml"
- import_tasks: "roles/config_terraform/tasks/execute.yml"