---
- include_vars: "../vars/internal.yml"
- include_vars: "../roles/stackhead_module_api/vars/main.yml"

- import_tasks: "../roles/stackhead_setup/tasks/facts-load.yml"
  ignore_errors: yes

- import_tasks: "../roles/stackhead_module_api/tasks_internal/load-all-modules-config.yml"

- import_tasks: "../roles/stackhead_setup/tasks/facts-deploy.yml"

- import_tasks: "../roles/stackhead_setup/tasks/setup-basic.yml"

- import_tasks: "../roles/stackhead_setup/tasks/setup-user.yml"

- import_tasks: "../roles/stackhead_setup/tasks/setup-folders.yml"

- import_tasks: "../roles/stackhead_setup/tasks/setup-terraform.yml"

- import_tasks: "../roles/stackhead_module_api/tasks_internal/setup.yml"
