---
- include_vars: "{{ playbook_dir }}/config.yaml"

- import_tasks: "roles/stackhead_setup/tasks/facts-load.yml"
  ignore_errors: yes

- import_tasks: "roles/stackhead_setup/tasks/facts-deploy.yml"

- import_tasks: "roles/stackhead_setup/tasks/setup-basic.yml"

- import_tasks: "roles/stackhead_setup/tasks/setup-user.yml"

- import_tasks: "roles/stackhead_setup/tasks/setup-folders.yml"

- import_tasks: "roles/stackhead_setup/tasks/setup-terraform.yml"

- name: "Setup {{ _stackhead__webserver }} webserver"
  include_tasks: "{{ roleinclude_path }}/tasks/setup.yml"
  vars:
    roleinclude_path: "roles/stackhead_webserver_{{ _stackhead__webserver }}"
    role_path: "{{ roleinclude_path }}"

- import_tasks: "roles/stackhead_setup/tasks/setup-docker.yml"