---
- name: Add stackhead group
  group:
    name: stackhead
    gid: "{{ STACKHEAD__GID }}"
    system: yes
    state: present
- name: Add stackhead user
  user:
    name: stackhead
    comment: StackHead system user
    uid: "{{ STACKHEAD__UID }}"
    groups: stackhead,www-data
    create_home: no
    state: present
- name: Generate stackhead sudoers permissions file
  blockinfile:
    path: '/etc/sudoers.d/stackhead'
    block: |
      %stackhead ALL= NOPASSWD: /bin/systemctl reload nginx
    mode: 0440
    create: yes
    state: present
    validate: 'visudo -cf %s'
- name: Set includedir in sudoers
  lineinfile:
    dest: /etc/sudoers
    line: "#includedir /etc/sudoers.d"
    state: present
    validate: "/usr/sbin/visudo -cf %s"