---
- name: Add stackhead group
  group:
    name: stackhead
    gid: "{{ STACKHEAD__GID }}"
    system: yes
    state: present
- name: Add stackhead user
  user:
    name: stackhead
    comment: StackHead system user
    uid: "{{ STACKHEAD__UID }}"
    groups: stackhead,www-data
    create_home: no
    home: "{{ stackhead__root_folder }}"
    state: present
- name: Set includedir in sudoers
  lineinfile:
    dest: /etc/sudoers
    line: "#includedir /etc/sudoers.d"
    state: present
    validate: "/usr/sbin/visudo -cf %s"
