---
- include_role:
    name: geerlingguy.php-versions
  vars:
    php_version: "{{ stackhead.capabilities.php.version }}"
- include_role:
    name: geerlingguy.php
  vars:
    php_enable_php_fpm: true
    php_enable_webserver: false