---
- name: Create StackHead root folder
  file:
    path: "{{ stackhead__root_folder }}"
    state: directory
    owner: stackhead
    group: stackhead
- name: Write StackHead version to server
  copy:
    content: "{{ lookup('file', '../../VERSION') }}"
    dest: "{{ stackhead__root_folder }}/VERSION"
    owner: stackhead
    group: stackhead
- name: Create certificates folder
  file:
    path: "{{ stackhead__certificates_folder }}"
    state: directory
    owner: stackhead
    group: stackhead
