---
- name: Create global Terraform folder
  file:
    path: "{{ stackhead__tf_root_folder }}"
    state: directory
    owner: stackhead
    group: stackhead
- name: Create Terraform plugin folder
  file:
    path: "{{ terraform_plugin_directory }}"
    state: directory
    owner: stackhead
    group: stackhead
- include_role:
    name: andrewrothstein.terraform
- name: Download Nginx provider
  get_url:
    url: https://github.com/getstackhead/terraform-nginx/releases/download/v1.0.0/terraform-provider-nginx
    dest: "{{ terraform_plugin_directory }}/terraform-provider-nginx"
    mode: '0755'
    owner: stackhead
    group: stackhead
    force: yes
- name: Copy patched acme-provider
  get_url:
    url: https://github.com/getstackhead/terraform-provider-acme/releases/download/v1.5.0-patched/terraform-provider-acme
    dest: "{{ terraform_plugin_directory }}/terraform-provider-acme_v1.5.0_x4"
    mode: '0755'
    owner: stackhead
    group: stackhead
    force: yes
- name: Create Terraform provider configurations
  template:
    src: "templates/terraform/terraform-providers.tf.j2"
    dest: "{{ stackhead__tf_root_folder }}/terraform-providers.tf"