---
- name: Create global Terraform folder
  file:
    path: "{{ stackhead__tf_root_folder }}"
    state: directory
    owner: stackhead
    group: stackhead
- include_role:
    name: andrewrothstein.terraform
  vars:
    terraform_ver: 0.13.3

# Setup Terraform components of modules
- import_tasks: "../roles/stackhead_module_api/tasks_internal/terraform.yml"

- name: Create Terraform provider configurations
  template:
    src: "{{ stackhead__templates }}/terraform/terraform-providers.tf.j2"
    dest: "{{ stackhead__tf_root_folder }}/terraform-providers.tf"

# Initial run applying settings from Terraform files created above
- import_tasks: "../roles/config_terraform/tasks/execute.yml"
