---
- name: Create global Terraform folder
  file:
    path: "{{ stackhead__tf_root_folder }}"
    state: directory
    owner: stackhead
    group: stackhead
- name: Create Terraform plugin folder
  file:
    path: "{{ terraform_plugin_directory }}"
    state: directory
    owner: stackhead
    group: stackhead
- include_role:
    name: andrewrothstein.terraform

# Setup Terraform components of modules
- include_vars:
    file: "roles/stackhead_webserver_{{ _stackhead__webserver }}/stackhead-module.yml"
    name: webserver_module
- name: "Download Terraform provider for {{ _stackhead__webserver }} webserver"
  get_url:
    url: "{{ webserver_module.terraform.provider.url }}"
    dest: "{{ terraform_plugin_directory }}/terraform-provider-{{ webserver_module.terraform.provider.name }}"
    mode: '0755'
    owner: stackhead
    group: stackhead
    force: yes
  when: webserver_module.terraform is defined and webserver_module.terraform.provider is defined and webserver_module.terraform.provider.name is defined and webserver_module.terraform.provider.url is defined

- name: Copy patched acme-provider
  get_url:
    url: https://github.com/getstackhead/terraform-provider-acme/releases/download/v1.5.0-patched/terraform-provider-acme
    dest: "{{ terraform_plugin_directory }}/terraform-provider-acme_v1.5.0_x4"
    mode: '0755'
    owner: stackhead
    group: stackhead
    force: yes
- name: Create Terraform provider configurations
  template:
    src: "{{ stackhead__templates }}/terraform/terraform-providers.tf.j2"
    dest: "{{ stackhead__tf_root_folder }}/terraform-providers.tf"

# Initial run applying settings from Terraform files created above
- import_tasks: "roles/config_terraform/tasks/execute.yml"