---
- name: Create global Terraform folder
  file:
    path: "{{ stackhead__tf_root_folder }}"
    state: directory
    owner: stackhead
    group: stackhead
- name: Create system Terraform folder
  file:
    path: "{{ stackhead__system_tf_root_folder }}"
    state: directory
    owner: stackhead
    group: stackhead
- include_role:
    name: andrewrothstein.terraform
  vars:
    terraform_ver: 0.13.3

# Setup Terraform components of modules
- import_tasks: "../roles/stackhead_module_api/tasks_internal/terraform.yml"
- import_tasks: "../roles/config_terraform/tasks/generate-providers.yml"

# Initial run applying settings from Terraform files created above
- import_tasks: "../roles/config_terraform/tasks/execute.yml"

# Setup crontask for applying Terraform files every 5 minutes
- shell: which terraform
  register: terraform_bin_abs_path
- name: Create StackHead Terraform apply service
  include_role:
    name: openstack_systemd_service
  vars:
    systemd_services:
      - service_name: stackhead-apply-terraform
        service_type: oneshot
        working_directory: "{{ stackhead__tf_root_folder }}"
        environment:
          TF_IN_AUTOMATION: 1
        execstarts:
          - "{{ terraform_bin_abs_path.stdout }} apply -auto-approve -input=false"
        timer:
          state: "started"
          options:
            Unit: "stackhead-apply-terraform.service"
            OnActiveSec: 1sec
            OnUnitActiveSec: 5min
            Persistent: true
