name: Release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    env:
      GIT_AUTHOR_EMAIL: 64205253+stackhead-bot@users.noreply.github.com
      GIT_AUTHOR_NAME: stackhead-bot
      GIT_COMMITTER_EMAIL: 64205253+stackhead-bot@users.noreply.github.com
      GIT_COMMITTER_NAME: stackhead-bot
    steps:
      - uses: actions/checkout@v2
      #- uses: actions/setup-go@v2
      #  with:
      #    go-version: 1.15
      #- uses: go-semantic-release/action@v1
      #  id: semrel
      #  with:
      #    github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: npm install
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
