name: Test CLI

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
    branches:
      - master
      - next
    paths:
      - cli/**
      - .github/workflows/test-cli.yml

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build
        working-directory: cli
        run: go build -v -o bin/stackhead-cli

      - uses: actions/upload-artifact@v2
        with:
          name: stackhead-cli
          path: cli/bin/stackhead-cli

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Test
        working-directory: cli
        run: go test ./...
